### PR TITLE
HTML structure changes & some initial CSS styling

### PR DESCRIPTION
**Pull request by bertez**
Work in progress, I made a bunch of changes to the HTML structure.

You can see the result here:

http://anavallasuiza.github.com/popcorn-docs/

### CODE REVIEW

**Comment by dseif** [comment]
Hey Berto,

I can't thank you guys enough for all your work on this, it looks amazing!
 I am in the process of merging this now and want to put it up on the site
ASAP.  I noticed a few odd things with some of the page links ( this one in
particular http://anavallasuiza.github.com/popcorn-docs/getting-started/ )
in that the text for the link seems to wrap to 2 lines and gets cut off
oddly ( on chrome ) and there is an odd split when viewing in Firefox.  Do
you see something similar?  I can send a screenshot if im not explaining
myself well enough, just let me know.

Other than that this is amazing, thanks a ton for all of your work, the
docs are much better because of it!

Dave

On Fri, Dec 23, 2011 at 10:58 AM, Berto Yez <
reply@reply.github.com

**Comment by bertez** [comment]
Oh, I see that bug. We'll fix it today and also fine tune some other details.

I'll update you later today.

**Comment by bertez** [comment]
Sorry for the delay, been busy like hell

The Chrome bug should be fixed.

Also did some small changes.

**Comment by dseif** [comment]
Thanks Berto! Going to pull in the changes after lunch, thanks again!
On Jan 12, 2012 1:13 PM, "Berto Yez" <
reply@reply.github.com>
wrote:

**Comment by dseif** [comment]
This looks great! Everything seems to be working fine on the desktop version. I'm looking here and from what I can tell you guys created a mobile version as well ( which is amazing ).  I am trying to trigger the mobile version to show by resizing and what not ( also tried directly on my phone ) but can't seem to get it to work.  Is there something I'm doing wrong?

**Comment by bertez** [comment]
My mistake,
will fix that this weekend

**Pull request merged**
